### PR TITLE
#9: Allow custom tar archive path

### PR DESCRIPTION
**Pull request by reynoldsalec**
This PR allows users to specify a custom URL for the tar archive targets (ex: `target_darwin_amd64`). If a boolean is provided, `homebrew-releaser` will default to the old behavior of generating the standard URL format (ex: `https://github.com/{GITHUB_OWNER}/{GITHUB_REPO}/releases/download/{version}/{GITHUB_REPO}-{version_no_v}-darwin-amd64.tar.gz`).

I believe this directly addresses the concern in issue #9; we certainly ran up against this problem when using `homebrew-releaser`, since we have tar archives in a fairly custom format. This also could allow users who want to host their releasable archive somewhere outside of GitHub.

I think there might be a more concise way of doing this PR, but felt that it might require more refactoring than I wanted to do. Happy to reformat!

### CODE REVIEW

**Comment by reynoldsalec** [comment]
Ah looks like I need to get some greenlights on these tests; closing this out until I get those to pass.

**Comment by Justintime50** [comment]
Ooo this looks good, thanks for your contribution! I wanted to allow custom paths when I set out to do this but didn't have an immediately great way to accomplish it. This seems to do just that without a ton of code.

I'd like to see some unit tests added to ensure this works as expected. You can check the current batch of tests for examples. TLDR: I want to make sure that the formula generation works as intended - if done correctly there should be a couple new formula test files generated due to the new tests added.

It also looks like the linter and the test suite failed, you'll want to address those as well. If tests are added and the linter is fixed, I'll take another look.

**Comment by reynoldsalec** [comment]
Jinx! Thanks @Justintime50, I'll do that and reopen when I get a chance.

**Comment by Justintime50** [comment]
> Ah looks like I need to get some greenlights on these tests; closing this out until I get those to pass.

No worries! You can always put a PR into draft mode too instead of closing which may be the more appropriate option in the future.

**Pull request closed without merging**
